### ISSUE TITLE
About the triplet

### ISSUE THREAD

**Issue by Zhang-GK** [JXZe/DualVD#13]
The triplet is expressed as embeddings. Is there any way to get the textual form? Thanks in advance.

**Comment by JXZe** [comment]
Thanks for your attention for our work.

As for the label of relation, you can refer [Large-Scale-VRD](https://github.com/jz462/Large-Scale-VRD.pytorch) for details.

As for the label of visual object, you can refer [Faster-rcnn](https://github.com/peteanderson80/bottom-up-attention) for details.

What's more, we utilize the relation embedding to capture the visual relationship, rather than the textual label. Since the  relation embedding contains more visual objects information, which can be viewed as a more soft strategy to construct visual relationship.

**Comment by Zhang-GK** [comment]
I get it！Thanks again！
